// A single line of subtitle
export interface SubtitleEntry {
  id: string;
  start: number; // Seconds (e.g., 12.4)
  end: number;   // Seconds (e.g., 15.1)
  text: string;
}

// Metadata for a subtitle track available on the video
export interface SubtitleTrack {
  id: string;
  languageCode: string; // e.g., "en", "pl"
  languageName: string; // e.g., "English", "Polish"
  isAutoGenerated?: boolean;
}

// The generic contract that YouTube (and future platforms) MUST implement
export interface PlatformAdapter {
  // Check if we are currently on a valid video page
  isVideoPage(): boolean;
  
  // Get the HTML <video> element so we can attach event listeners
  getVideoElement(): HTMLVideoElement | null;
  
  // Fetch available tracks for the current video
  getAvailableTracks(): Promise<SubtitleTrack[]>;
  
  // Fetch the actual subtitle content for a specific track
  fetchSubtitleEntries(track: SubtitleTrack): Promise<SubtitleEntry[]>;
}