import { YouTubeAdapter } from '../platforms/youtube/YoutubeAdapter.ts';
import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import SubtitleOverlay from './SubtitleOverlay';
import { SubtitleEngine } from '../core/engine/SubtitleEngine';
import { getSettings } from '../shared/storage';

const adapter = new YouTubeAdapter();
const CAPTURE_TIMEOUT_MS = 6000;

type LiveTrack = { languageCode: string; isAutoGenerated: boolean };

const App = () => {
  const [displayPrimary, setDisplayPrimary] = useState('');
  const [displaySecondary, setDisplaySecondary] = useState('');
  const [isEnabled, setEnabled] = useState(true);
  const engine = useRef(new SubtitleEngine());

  const pendingResolve = useRef<((data: string | null) => void) | null>(null);
  const pendingTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pendingMatcher = useRef<((url: string) => boolean) | null>(null);
  const pendingTracksResolve = useRef<((tracks: LiveTrack[]) => void) | null>(null);

  const getLiveTracks = (): Promise<LiveTrack[]> => {
    return new Promise((resolve) => {
      pendingTracksResolve.current = resolve;
      window.postMessage({ type: 'SUBLINGO_GET_TRACKS' }, '*');
      setTimeout(() => {
        if (pendingTracksResolve.current) {
          pendingTracksResolve.current = null;
          resolve([]);
        }
      }, 2000);
    });
  };

  const waitForCapture = (matcher: (url: string) => boolean): Promise<string | null> => {
    return new Promise((resolve) => {
      pendingResolve.current = resolve;
      pendingMatcher.current = matcher;
      pendingTimer.current = setTimeout(() => {
        console.warn('[SubLingo] Capture timed out waiting for track');
        pendingResolve.current = null;
        pendingMatcher.current = null;
        resolve(null);
      }, CAPTURE_TIMEOUT_MS);
    });
  };

  const requestTrack = async (sourceLangCode: string, isTranslation: boolean, targetLangCode?: string): Promise<string | null> => {
    const matcher = (url: string) => {
      if (isTranslation && targetLangCode) return url.includes(`tlang=${targetLangCode}`);
      return url.includes(`lang=${sourceLangCode}`) && !url.includes('tlang=');
    };
    const capturePromise = waitForCapture(matcher);
    window.postMessage({ type: 'SUBLINGO_SET_PLAYER_LANG', sourceLangCode, isTranslation, targetLangCode }, '*');
    return capturePromise;
  };

  const requestTrackWithRetry = async (
  sourceLangCode: string,
  isTranslation: boolean,
  targetLangCode: string | undefined,
  maxRetries = 2
): Promise<string | null> => {
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    if (attempt > 0) {
      console.warn(`[SubLingo] Retry ${attempt} for`, sourceLangCode, isTranslation ? `-> ${targetLangCode}` : '');
      await new Promise(r => setTimeout(r, 500));
    }
    const raw = await requestTrack(sourceLangCode, isTranslation, targetLangCode);
    if (raw) return raw;
  }
  return null;
};

  const resolveTrackConfig = (tracks: LiveTrack[], targetCode: string, primaryLanguage: string) => {
    const baseCode = targetCode.split('-')[0];
    const direct = tracks.find(t => t.languageCode === targetCode)
      ?? tracks.find(t => t.languageCode.startsWith(baseCode));
    if (direct) return { sourceLangCode: direct.languageCode, isTranslation: false, targetLangCode: undefined as string | undefined };

    const sourceTrack =
      tracks.find(t => t.languageCode.startsWith(primaryLanguage.split('-')[0])) ??
      tracks.find(t => t.languageCode.startsWith('en')) ??
      tracks[0];

    if (!sourceTrack) return null;
    return { sourceLangCode: sourceTrack.languageCode, isTranslation: true, targetLangCode: baseCode };
  };

  const loadSubtitles = async () => {
  const s = await getSettings();
  setEnabled(s.enabled);
  if (!s.enabled) return;

  const tracks = await getLiveTracks();
  if (tracks.length === 0) {
    console.warn('[SubLingo] No caption tracks found for this video');
    engine.current.setPrimaryEntries([]);
    engine.current.setSecondaryEntries([]);
    return;
  }

  const primaryConfig = resolveTrackConfig(tracks, s.primaryLanguage, s.primaryLanguage);
  const secondaryConfig = resolveTrackConfig(tracks, s.secondaryLanguage, s.primaryLanguage);

  if (primaryConfig) {
    const primaryRaw = await requestTrackWithRetry(primaryConfig.sourceLangCode, primaryConfig.isTranslation, primaryConfig.targetLangCode);
    engine.current.setPrimaryEntries(primaryRaw ? adapter.parse(primaryRaw) : []);
    console.log('[SubLingo] Primary captured:', !!primaryRaw);
  } else {
    console.warn('[SubLingo] Could not resolve a primary track config');
  }

  // Small gap before the next player command — the player appears to
  // occasionally drop a setOption call that arrives while it's still
  // settling from the previous one.
  await new Promise(r => setTimeout(r, 300));

  if (secondaryConfig) {
    const secondaryRaw = await requestTrackWithRetry(secondaryConfig.sourceLangCode, secondaryConfig.isTranslation, secondaryConfig.targetLangCode);
    engine.current.setSecondaryEntries(secondaryRaw ? adapter.parse(secondaryRaw) : []);
    console.log('[SubLingo] Secondary captured:', !!secondaryRaw);
  } else {
    console.warn('[SubLingo] Could not resolve a secondary track config');
  }
};

  useEffect(() => {
    let currentVideo: HTMLVideoElement | null = null;
    let handleTimeUpdate: (() => void) | null = null;

    const attachToVideo = () => {
      const video = adapter.getVideoElement();
      if (!video || video === currentVideo) return;
      if (currentVideo && handleTimeUpdate) currentVideo.removeEventListener('timeupdate', handleTimeUpdate);

      currentVideo = video;
      handleTimeUpdate = () => {
        const { primaryText, secondaryText } = engine.current.getActiveEntries(video.currentTime);
        setDisplayPrimary(primaryText);
        setDisplaySecondary(secondaryText);
      };
      video.addEventListener('timeupdate', handleTimeUpdate);
    };

    // YouTube is an SPA — clicking to a new video doesn't reload the page,
    // so this content script's one-time mount never sees it. yt-navigate-finish
    // is YouTube's own event marking a completed in-app navigation.
    const handleNavigate = () => {
      console.log('[SubLingo] yt-navigate-finish — reloading subtitles for new video');
      engine.current.setPrimaryEntries([]);
      engine.current.setSecondaryEntries([]);
      setDisplayPrimary('');
      setDisplaySecondary('');
      attachToVideo();
      loadSubtitles();
    };

    const handleMessage = (event: MessageEvent) => {
      if (event.source !== window) return;

      if (event.data.type === 'SUBLINGO_TRACKS' && pendingTracksResolve.current) {
        const resolve = pendingTracksResolve.current;
        pendingTracksResolve.current = null;
        resolve(event.data.tracks ?? []);
        return;
      }

      if (event.data.type === 'SUBLINGO_DATA') {
        const url = event.data.url as string;
        if (pendingResolve.current && pendingMatcher.current) {
          if (pendingMatcher.current(url)) {
            if (pendingTimer.current) clearTimeout(pendingTimer.current);
            const resolve = pendingResolve.current;
            pendingResolve.current = null;
            pendingMatcher.current = null;
            resolve(event.data.data);
          } else {
            console.log('[SubLingo] Ignored non-matching timedtext packet:', url);
          }
        }
      }
    };

    attachToVideo();
    loadSubtitles();

    window.addEventListener('message', handleMessage);
    window.addEventListener('yt-navigate-finish', handleNavigate);
    chrome.storage.onChanged.addListener(loadSubtitles);

    return () => {
      window.removeEventListener('message', handleMessage);
      window.removeEventListener('yt-navigate-finish', handleNavigate);
      chrome.storage.onChanged.removeListener(loadSubtitles);
      if (currentVideo && handleTimeUpdate) currentVideo.removeEventListener('timeupdate', handleTimeUpdate);
    };
  }, []);

  if (!isEnabled) return null;
  return <SubtitleOverlay primaryText={displayPrimary} secondaryText={displaySecondary} />;
};

function injectUI() {
  if (document.getElementById('sublingo-root')) return;
  const style = document.createElement('style');
  style.textContent = `.ytp-caption-window-container { display: none !important; }`;
  (document.head || document.documentElement).appendChild(style);

  const container = document.createElement('div');
  container.id = 'sublingo-root';
  Object.assign(container.style, {
    position: 'fixed', bottom: '15%', left: '0', right: '0',
    display: 'flex', justifyContent: 'center', zIndex: '2147483647', pointerEvents: 'none'
  });
  document.body.appendChild(container);
  const shadow = container.attachShadow({ mode: 'open' });
  const root = document.createElement('div');
  shadow.appendChild(root);
  createRoot(root).render(<App />);
}
if (document.body) injectUI();
else window.addEventListener('load', injectUI);