import { YouTubeAdapter } from '../platforms/youtube/YoutubeAdapter.ts'; 
import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import SubtitleOverlay from './SubtitleOverlay';
import { SubtitleEngine } from '../core/engine/SubtitleEngine';
import { getSettings } from '../shared/storage';

const adapter = new YouTubeAdapter();

const App = () => {
  const [displayPrimary, setDisplayPrimary] = useState('');
  const [displaySecondary, setDisplaySecondary] = useState('');
  const [isEnabled, setEnabled] = useState(true);
  const engine = useRef(new SubtitleEngine());

  // Function to request both languages from YouTube's server
  const triggerFetchSequence = async () => {
    const s = await getSettings();
    setEnabled(s.enabled);
    if (!s.enabled) return;

    const tracks = await adapter.getAvailableTracks();

    const getTrackConfig = (targetCode: string) => {
      const hasManual = tracks.find(t => t.languageCode === targetCode);
      const baseCode = targetCode.split('-')[0];
      const hasASR = tracks.find(t => t.languageCode.startsWith(baseCode) && t.isAutoGenerated);

      if (hasManual) return { langCode: targetCode, isTranslation: false };
      if (hasASR) return { langCode: hasASR.languageCode, isTranslation: false };
      return { langCode: baseCode, isTranslation: true }; // Force Google Translate
    };

    // Sequence: Fetch Primary, then Secondary
    const primaryConfig = getTrackConfig(s.primaryLanguage);
    const secondaryConfig = getTrackConfig(s.secondaryLanguage);

    window.postMessage({ type: 'SUBLINGO_SET_PLAYER_LANG', ...primaryConfig }, '*');
    
    setTimeout(() => {
      window.postMessage({ type: 'SUBLINGO_SET_PLAYER_LANG', ...secondaryConfig }, '*');
    }, 1200);
  };

  useEffect(() => {
    const video = adapter.getVideoElement();
    if (!video) return;

    triggerFetchSequence();

    const handleMessage = async (event: MessageEvent) => {
      if (event.source !== window || event.data.type !== 'SUBLINGO_DATA') return;
      
      const parsed = adapter.parse(event.data.data);
      if (parsed.length === 0) return;

      const s = await getSettings();
      const url = event.data.url;
      
      // SMART MATCHING: Handle both lang= and tlang= (translations)
      const pBase = s.primaryLanguage.split('-')[0];
      const sBase = s.secondaryLanguage.split('-')[0];

      const isPrimaryPacket = url.includes(`lang=${pBase}`) || url.includes(`tlang=${pBase}`);
      const isSecondaryPacket = url.includes(`lang=${sBase}`) || url.includes(`tlang=${sBase}`);

      if (isPrimaryPacket) {
        engine.current.setPrimaryEntries(parsed);
        console.log('[SubLingo] Caught Primary:', pBase);
      } 
      
      if (isSecondaryPacket) {
        engine.current.setSecondaryEntries(parsed);
        console.log('[SubLingo] Caught Secondary:', sBase);
      }
    };

    window.addEventListener('message', handleMessage);
    chrome.storage.onChanged.addListener(triggerFetchSequence);

    video.addEventListener('timeupdate', () => {
      const { primaryText, secondaryText } = engine.current.getActiveEntries(video.currentTime);
      setDisplayPrimary(primaryText);
      setDisplaySecondary(secondaryText);
    });

    return () => {
      window.removeEventListener('message', handleMessage);
      chrome.storage.onChanged.removeListener(triggerFetchSequence);
    };
  }, []);

  if (!isEnabled) return null;
  return <SubtitleOverlay primaryText={displayPrimary} secondaryText={displaySecondary} />;
};

function injectUI() {
  if (document.getElementById('sublingo-root')) return;
  const style = document.createElement('style');
  style.textContent = `.ytp-caption-window-container { display: none !important; }`;
  (document.head || document.documentElement).appendChild(style);

  const container = document.createElement('div');
  container.id = 'sublingo-root';
  Object.assign(container.style, {
    position: 'fixed', bottom: '15%', left: '0', right: '0',
    display: 'flex', justifyContent: 'center', zIndex: '2147483647', pointerEvents: 'none'
  });
  document.body.appendChild(container);
  const shadow = container.attachShadow({ mode: 'open' });
  const root = document.createElement('div');
  shadow.appendChild(root);
  createRoot(root).render(<App />);
}
if (document.body) injectUI();
else window.addEventListener('load', injectUI);