import type { PlatformAdapter, SubtitleEntry, SubtitleTrack } from '../../core/types/subtitles';

export class YouTubeAdapter implements PlatformAdapter {
  isVideoPage() { return window.location.pathname === '/watch'; }
  getVideoElement() { return document.querySelector<HTMLVideoElement>('video.html5-main-video'); }

  async getAvailableTracks(): Promise<SubtitleTrack[]> {
    if (!this.isVideoPage()) return [];
    const scripts = Array.from(document.getElementsByTagName('script'));
    const playerScript = scripts.find((s) => s.textContent?.includes('ytInitialPlayerResponse'));
    if (!playerScript?.textContent) return [];
    try {
      const regex = /ytInitialPlayerResponse\s*=\s*({.+?});/;
      const match = playerScript.textContent.match(regex);
      if (!match) return [];
      const data = JSON.parse(match[1]);
      const captionTracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!captionTracks) return [];
      return captionTracks.map((track: any) => ({
        id: track.baseUrl,
        languageCode: track.languageCode,
        languageName: track.name.simpleText,
        isAutoGenerated: track.kind === 'asr',
      }));
    } catch (e) { return []; }
  }

  async fetchSubtitleEntries(track: SubtitleTrack): Promise<SubtitleEntry[]> {
    return new Promise((resolve) => {
      const requestId = Math.random().toString(36).substring(7);
      const url = track.id.includes('fmt=json3') ? track.id : `${track.id}&fmt=json3`;

      const onMessage = (event: MessageEvent) => {
        if (event.data.type === 'SUBLINGO_FETCH_RESPONSE' && event.data.requestId === requestId) {
          window.removeEventListener('message', onMessage);
          
          if (!event.data.success || !event.data.data) {
            console.error('[SubLingo] Hook returned 0 chars. Blocked by YouTube.');
            resolve([]);
            return;
          }

          const rawData = event.data.data.trim();
          
          // CRITICAL: Check if data is empty before parsing
          if (rawData.length === 0) {
            console.error('[SubLingo] Data body is empty.');
            resolve([]);
            return;
          }

          try {
            if (rawData.startsWith('<')) {
              resolve(this.parseXML(rawData));
            } else {
              resolve(this.parseJSON(rawData));
            }
          } catch (e) {
            console.error('[SubLingo] Parser error:', e);
            resolve([]);
          }
        }
      };

      window.addEventListener('message', onMessage);

      window.postMessage({
        type: 'SUBLINGO_REQUEST_FETCH',
        requestId: requestId,
        url: url
      }, '*');
    });
  }
  
  // (Keep your parseXML and parseJSON methods from before, they were perfect)

  private parseXML(xmlText: string): SubtitleEntry[] {
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlText, 'text/xml');
    const textNodes = Array.from(xmlDoc.getElementsByTagName('text'));
    return textNodes.map((node, index) => ({
      id: index.toString(),
      start: parseFloat(node.getAttribute('start') || '0'),
      end: parseFloat(node.getAttribute('start') || '0') + parseFloat(node.getAttribute('dur') || '0'),
      text: node.textContent || '',
    }));
  }

  public parseJSON(jsonText: string): SubtitleEntry[] {
    const data = JSON.parse(jsonText);
    return data.events
      .filter((event: any) => event.segs)
      .map((event: any, index: number) => ({
        id: index.toString(),
        start: event.tStartMs / 1000,
        end: (event.tStartMs + (event.dDurationMs || 0)) / 1000,
        text: event.segs.map((s: any) => s.utf8).join('').trim(),
      }));
  }
}