import type { PlatformAdapter, SubtitleEntry, SubtitleTrack } from '../../core/types/subtitles';

export class YouTubeAdapter implements PlatformAdapter {
  isVideoPage() { return window.location.pathname === '/watch'; }
  getVideoElement() { return document.querySelector<HTMLVideoElement>('video.html5-main-video'); }

  async getAvailableTracks(): Promise<SubtitleTrack[]> {
    if (!this.isVideoPage()) return [];
    const scripts = Array.from(document.getElementsByTagName('script'));
    const playerScript = scripts.find((s) => s.textContent?.includes('ytInitialPlayerResponse'));
    if (!playerScript?.textContent) return [];
    try {
      const regex = /ytInitialPlayerResponse\s*=\s*({.+?});/;
      const match = playerScript.textContent.match(regex);
      if (!match) return [];
      const data = JSON.parse(match[1]);
      const captionTracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!captionTracks) return [];
      return captionTracks.map((track: any) => ({
        id: track.baseUrl,
        languageCode: track.languageCode,
        languageName: track.name.simpleText,
        isAutoGenerated: track.kind === 'asr',
      }));
    } catch (e) { return []; }
  }

  async fetchSubtitleEntries(track: SubtitleTrack): Promise<SubtitleEntry[]> {
    try {
      const videoId = new URLSearchParams(window.location.search).get('v');
      if (!videoId) throw new Error('Video ID not found');

      // THE LEGACY API: No signatures, no tokens, no session needed.
      // This works 99% of the time for all users (Premium or not).
      const legacyUrl = `https://video.google.com/timedtext?v=${videoId}&lang=${track.languageCode}${track.isAutoGenerated ? '&kind=asr' : ''}`;
      
      console.log('[SubLingo] Fetching from Legacy Public API:', legacyUrl);

      const response: any = await chrome.runtime.sendMessage({
        type: 'FETCH_SUBTITLES',
        url: legacyUrl
      });

      if (!response || !response.success || !response.data || response.data.length < 100) {
        throw new Error('Legacy API returned no data');
      }

      // XML PARSER (Legacy API returns XML)
      const parser = new DOMParser();
      const xmlDoc = parser.parseFromString(response.data, 'text/xml');
      const textNodes = Array.from(xmlDoc.getElementsByTagName('text'));

      return textNodes.map((node, index) => {
        const start = parseFloat(node.getAttribute('start') || '0');
        const dur = parseFloat(node.getAttribute('dur') || '0');
        const tempDiv = document.createElement('div');
        tempDiv.innerHTML = node.textContent || '';
        return {
          id: index.toString(),
          start: start,
          end: start + dur,
          text: tempDiv.textContent?.trim() || '',
        };
      });
    } catch (e: any) {
      console.error('[SubLingo] Fetch Error:', e.message);
      return [];
    }
  }
  
  // (Keep your parseXML and parseJSON methods from before, they were perfect)

  private parseXML(xmlText: string): SubtitleEntry[] {
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlText, 'text/xml');
    const textNodes = Array.from(xmlDoc.getElementsByTagName('text'));
    return textNodes.map((node, index) => ({
      id: index.toString(),
      start: parseFloat(node.getAttribute('start') || '0'),
      end: parseFloat(node.getAttribute('start') || '0') + parseFloat(node.getAttribute('dur') || '0'),
      text: node.textContent || '',
    }));
  }

  public parseJSON(jsonText: string): SubtitleEntry[] {
    const data = JSON.parse(jsonText);
    return data.events
      .filter((event: any) => event.segs)
      .map((event: any, index: number) => ({
        id: index.toString(),
        start: event.tStartMs / 1000,
        end: (event.tStartMs + (event.dDurationMs || 0)) / 1000,
        text: event.segs.map((s: any) => s.utf8).join('').trim(),
      }));
  }
}