import type { PlatformAdapter, SubtitleEntry, SubtitleTrack } from '../../core/types/subtitles';

export class YouTubeAdapter implements PlatformAdapter {
  isVideoPage() { return window.location.pathname === '/watch'; }
  getVideoElement() { return document.querySelector<HTMLVideoElement>('video.html5-main-video'); }

  async getAvailableTracks(): Promise<SubtitleTrack[]> {
    const scripts = Array.from(document.getElementsByTagName('script'));
    const playerScript = scripts.find((s) => s.textContent?.includes('ytInitialPlayerResponse'));
    if (!playerScript?.textContent) return [];
    try {
      const regex = /ytInitialPlayerResponse\s*=\s*({.+?});/;
      const match = playerScript.textContent.match(regex);
      if (!match) return [];
      const data = JSON.parse(match[1]);
      const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!tracks) return [];
      return tracks.map((t: any) => ({
        id: t.baseUrl,
        languageCode: t.languageCode,
        languageName: t.name.simpleText,
        isAutoGenerated: t.kind === 'asr',
      }));
    } catch (e) { return []; }
  }

  // Builds a translated-track URL from a base track's URL (e.g. force Polish via English base)
  buildTranslationUrl(baseTrackUrl: string, targetLangCode: string): string {
    const url = new URL(baseTrackUrl);
    url.searchParams.set('tlang', targetLangCode);
    return url.toString();
  }

  public parse(rawData: string): SubtitleEntry[] {
    if (!rawData || rawData.trim().length < 10) return [];
    try {
      if (rawData.trim().startsWith('<')) {
        const parser = new DOMParser();
        const xmlDoc = parser.parseFromString(rawData, 'text/xml');
        const textNodes = Array.from(xmlDoc.getElementsByTagName('text'));
        return textNodes.map((node, index) => ({
          id: index.toString(),
          start: parseFloat(node.getAttribute('start') || '0'),
          end: parseFloat(node.getAttribute('start') || '0') + parseFloat(node.getAttribute('dur') || '0'),
          text: node.textContent || '',
        }));
      } else {
        const data = JSON.parse(rawData);
        if (!data.events) return [];
        return data.events
          .filter((event: any) => event.segs)
          .map((event: any, index: number) => ({
            id: index.toString(),
            start: event.tStartMs / 1000,
            end: (event.tStartMs + (event.dDurationMs || 0)) / 1000,
            text: event.segs.map((s: any) => s.utf8).join('').trim(),
          }));
      }
    } catch (e) { return []; }
  }

  async fetchSubtitleEntries(): Promise<SubtitleEntry[]> { return []; }
}